name: aquaminity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # --- ADD THIS LINE ---
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

# --- ADD THIS SECTION AT THE VERY BOTTOM ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png" #Sets it in the foreground for Android
  remove_alpha_ios: true # Optional: removes alpha channel for iOS icons